# Tensorflow Documentation Sandbox 

Playground for documentation 

### Session

In [1]:
import tensorflow as tf

# Build a graph
a = tf.constant(5.0)
b = tf.constant(6.0)

c = a * b

#Launch the graph in a session.
sess = tf.Session()

#Evaluate the tensor 'c'
print(sess.run(c))

30.0


It is important to release these resources when they are no longer required. This can be done using the tf.Session.close() method

In [2]:
# Using the close method
sess = tf.Session()
sess.run(c)
sess.close()

#Using the context manager
with tf.Session() as sess:
    sess.run(c)

### Variables 

reference: https://www.tensorflow.org/programmers_guide/variables 

- Represents a tensor whose value can be changed by runnning ops on it.
- Unlike, tf.Tensor objects, a ``tf.Variable`` exists out the context of a single session.run call 
- Stores a presistent tensor. 

To create a variable, use the tf.get_variable() method

In [3]:
my_variable = tf.get_variable("my_variable", [1,2,3])

By default, these will by of dtype float32, and the initial values randomized using the tf.glorot_uniform_initializer

We can initialize the values of using different initializers 

In [4]:
my_int_variable = tf.get_variable("my_int_variable", [1,2,3], dtype=tf.int32, initializer=tf.zeros_initializer)

In [5]:
other_variable = tf.get_variable("other_variable", dtype=tf.int32, initializer=tf.constant([23,42]))

#### Using variables 




In [6]:
v = tf.get_variable("v", shape=(), initializer=tf.zeros_initializer())
w = v + 1  # w is a tf.Tensor which is computed based on the value of v.
           # Any time a variable is used in an expression it gets automatically
           # converted to a tf.Tensor representing its value.

**Note** There is a difference in using tf.Variable() and tf.get_variable(). See here: https://stackoverflow.com/questions/37098546/difference-between-variable-and-get-variable-in-tensorflow 

# Placeholder

Reference: https://www.tensorflow.org/api_docs/python/tf/placeholder 

In [7]:
import tensorflow as tf
import numpy as np

x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

with tf.Session() as sess:
#   print(sess.run(y))  # ERROR: will fail because x was not fed.

  rand_array = np.random.rand(1024, 1024)
  print(sess.run(y, feed_dict={x: rand_array}))  # Will succeed.

[[ 251.18945312  249.89321899  257.1477356  ...,  260.36242676  256.9755249
   250.92588806]
 [ 253.71710205  256.31854248  260.19198608 ...,  261.63299561
   260.51138306  255.90933228]
 [ 248.76158142  249.50053406  257.25646973 ...,  250.21209717
   253.58320618  248.64038086]
 ..., 
 [ 245.64065552  248.19085693  250.21273804 ...,  252.24645996
   255.68386841  247.31021118]
 [ 251.14926147  253.87886047  256.6362915  ...,  260.31607056
   258.76513672  254.51991272]
 [ 246.53236389  242.37911987  249.32304382 ...,  248.03804016
   246.86373901  243.35105896]]


# tf.rand_normal

References:
- https://www.tensorflow.org/api_docs/python/tf/random_normal 
- https://www.tensorflow.org/api_guides/python/constant_op#Random_Tensors


In [11]:
# Create a tensor of shape [2, 3] consisting of random normal values, with mean
# -1 and standard deviation 4.
norm = tf.random_normal([2, 3], mean=-1, stddev=4)

# Shuffle the first dimension of a tensor
c = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(c)

# Each time we run these ops, different results are generated
sess = tf.Session()
print("Before setting a op-level seed:\n")
print(sess.run(norm))
print(sess.run(norm))

# Set an op-level seed to generate repeatable sequences across sessions.
norm = tf.random_normal([2, 3], seed=1234)
sess = tf.Session()
print("After setting a op-level seed:\n")
print(sess.run(norm), "\n")
print(sess.run(norm), "\n")
sess = tf.Session()
print(sess.run(norm), "\n")
print(sess.run(norm), "\n")


Before setting a op-level seed:

[[-8.45236588 -4.86988735 -3.19376016]
 [-2.93038106  5.39059544 -3.08960295]]
[[-5.038908    0.46627212 -1.55824661]
 [-3.93750358  2.93456221  4.88614035]]
After setting a op-level seed:

[[ 0.51340485 -0.25581399  0.65199131]
 [ 1.39236379  0.37256798  0.20336303]] 

[[ 0.96462417  0.34291974  0.24251089]
 [ 1.05785966  1.65749764  0.82108968]] 

[[ 0.51340485 -0.25581399  0.65199131]
 [ 1.39236379  0.37256798  0.20336303]] 

[[ 0.96462417  0.34291974  0.24251089]
 [ 1.05785966  1.65749764  0.82108968]] 



# Definition of rank and shape of a tensor

Reference: https://www.tensorflow.org/programmers_guide/tensors#shape 

# Constant value tensors 

Reference: https://www.tensorflow.org/versions/r0.12/api_docs/python/constant_op/constant_value_tensors 

# Shapes and Shaping 

Reference: https://www.tensorflow.org/versions/r0.12/api_docs/python/array_ops/shapes_and_shaping 

The **tf.shape()** method shows the shape of the matrix: 

In [17]:
t = [[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]
tf.shape(t)

# shape(t) ==> [2, 2, 3]

<tf.Tensor 'Shape_2:0' shape=(3,) dtype=int32>

The **tf.size()** method shows the total number of elements in the tensor 

In [19]:
tf.size(t)
# size(t) ==> 12

<tf.Tensor 'Size:0' shape=() dtype=int32>

The **tf.rank()** method returns the size of rank of the matrix (the number of dimensions):

In [20]:
tf.rank(t)
# rank(t) ==> 3

<tf.Tensor 'Rank:0' shape=() dtype=int32>

The **tf.reshape()** method is used to reshape a tensor

In [ ]:
# tensor 't' is [1, 2, 3, 4, 5, 6, 7, 8, 9]
# tensor 't' has shape [9]
reshape(t, [3, 3]) ==> [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]

# tensor 't' is [[[1, 1], [2, 2]],
#                [[3, 3], [4, 4]]]
# tensor 't' has shape [2, 2, 2]
reshape(t, [2, 4]) ==> [[1, 1, 2, 2],
                        [3, 3, 4, 4]]

# tensor 't' is [[[1, 1, 1],
#                 [2, 2, 2]],
#                [[3, 3, 3],
#                 [4, 4, 4]],
#                [[5, 5, 5],
#                 [6, 6, 6]]]
# tensor 't' has shape [3, 2, 3]
# pass '[-1]' to flatten 't'
reshape(t, [-1]) ==> [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6]

# -1 can also be used to infer the shape

# -1 is inferred to be 9:
reshape(t, [2, -1]) ==> [[1, 1, 1, 2, 2, 2, 3, 3, 3],
                         [4, 4, 4, 5, 5, 5, 6, 6, 6]]
# -1 is inferred to be 2:
reshape(t, [-1, 9]) ==> [[1, 1, 1, 2, 2, 2, 3, 3, 3],
                         [4, 4, 4, 5, 5, 5, 6, 6, 6]]
# -1 is inferred to be 3:
reshape(t, [ 2, -1, 3]) ==> [[[1, 1, 1],
                              [2, 2, 2],
                              [3, 3, 3]],
                             [[4, 4, 4],
                              [5, 5, 5],
                              [6, 6, 6]]]

# tensor 't' is [7]
# shape `[]` reshapes to a scalar
reshape(t, []) ==> 7